require('cl') in bin/rock
Was getting error when trying to create file from custom rock, so I
required cl. Error:

/usr/local/lib/node_modules/rock/bin/rock:35
if (err) cl.exit(1, err)
^
ReferenceError: cl is not defined